import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="px-2 text-sm">
      <h1 className="mb-4 text-center text-xl font-semibold text-primary lg:text-2xl">
        PRIVACY POLICY
      </h1>
      <p className="mb-2">
        The “AC Prime Brokers, Inc.” and its subsidiaries (individually and
        collectively referred to as &quot;AC Prime&quot;) are committed to
        safeguarding the privacy of their data subjects; this policy specifies
        how your personal data is dealt with. Using the digital platforms that
        are part and parcel of AC Prime implies that you accept the terms of
        this privacy policy.
      </p>
      <p className="mb-2">
        AC Prime, as your data controller, shall ensure that the obligations set
        forth by the Data Privacy Act of 2012 and its implementing rules and
        regulations are carried out through the processing of your personal
        information.
      </p>
      <p className="mb-2">
        This privacy policy applies only to information collected online through
        the official websites, mobile applications, and social media pages
        (collectively referred to as &quot;digital platforms&quot;) and not to
        information collected offline. We may amend this privacy policy at any
        time by publishing a new version on this website.
      </p>
      <h2 className="mb-2 mt-4 font-semibold">
        1. What Information We Collect
      </h2>
      <p className="mb-2">
        AC Prime reserves the right to collect, store, and use the following
        kinds of information:
      </p>
      <ul className="mb-4 list-disc pl-5">
        <li>Name</li>
        <li>Email Address</li>
        <li>Contact Number</li>
        <li>Geographical location</li>
        <li>IP address</li>
        <li>Browser type and version</li>
        <li>Operating system</li>
        <li>Referral source</li>
        <li>Length of visit</li>
        <li>Page views</li>
        <li>Website navigation; and</li>
        <li>Any other personal information that you opt to provide to us</li>
      </ul>
      <p className="mb-2">
        AC Prime reserves the right to collect information from its users when
        users browse the company&#39;s websites and submit questions through the
        Contact Us page.
      </p>

      <h2 className="mb-2 mt-4 font-semibold">
        2. What We Use Your Information For
      </h2>
      <p className="mb-2">
        The information we collect from you may be used in one of the following
        ways:
      </p>
      <ul className="mb-4 list-disc pl-5">
        <li>
          To personalize your experience. Your information helps us to better
          respond to your individual needs to improve our digital platforms. We
          continually strive to improve our offerings based on the information
          and feedback we receive from you.
        </li>
        <li>
          To improve customer service. Your information helps us to more
          effectively respond to your customer service requests and support your
          needs.
        </li>
        <li>
          To administer a contest, promotion, survey or other site feature.
        </li>
      </ul>
      <p className="mb-2">
        Two types information of user data gathered on the platform:
      </p>
      <ul className="mb-4 list-disc pl-5">
        <li>
          Information volunteered by users as part of the registration, KYC and
          ordering processes, which may include data regarding their permanent
          residence address, family relationships, and financial circumstances.
          Users can see what information they have volunteered through the
          relevant section in their Accounts screens or pages. The government
          regulations mandate the collection of this data and can not be waived.
        </li>
        <li>
          The information generated by users as a result of interacting with our
          platforms. This may include data such as Internet Protocol addresses,
          portfolio composition and value, and technical data regarding mobile
          user devices. We use this data to ensure that our systems are running
          smoothly.
        </li>
        <li>
          To send periodic emails. The email address you provide may be used to
          send you information and updates pertaining to receiving occasional
          company news, updates, related product or service information, etc.
        </li>
      </ul>
      <h2 className="mb-2 mt-4 font-semibold">
        3. How We Protect Your Information
      </h2>
      <p className="mb-2">
        AC Prime implements physical, technical, and organizational security
        measures aligned with industry standards in order to ensure the
        confidentiality, integrity, and availability of any personal data that
        is submitted to us.
      </p>
      <p className="mb-2">
        We train our employees on the best practices for handling your personal
        data. Whenever we engage other organizations to provide service to us,
        we require them to protect your personal data aligned with AC Prime’s
        security standards.
      </p>
      <p className="mb-2">
        It is important to note that data transmission over the Internet is, by
        nature, insecure and we cannot guarantee the security of data sent over
        the Internet. We are not responsible for any delays, crashes, and other
        problems caused by the Internet, your Internet Service Provider, and
        other parties involved in the transmission of data.
      </p>

      <h2 className="mb-2 mt-4 font-semibold">
        4. How We May Share Your Information
      </h2>
      <p className="mb-2">
        AC Prime, subject to specific lawful exceptions, shall not disclose,
        release or sell to third parties any personal data or information given
        or transmitted through the Internet. This does not include trusted third
        parties who provide assistance in operating the websites, conducting
        business as usual or servicing you, so long as those parties agree to
        keep this information confidential. We may also release your information
        when we believe release is appropriate to comply with the law, enforce
        our site policies, or protect our rights, property, or safety. However,
        non-personally identifiable visitor information may be provided to other
        parties for marketing, advertising, or other uses relevant to the brand.
      </p>
      <p className="mb-2">
        AC Prime shall not use personal data or information given or transmitted
        through the Internet for purposes other than what has been described on
        this website. However, due to the nature of the Internet as an unsecured
        medium of communication, the company reserves the right to refrain from
        giving out an absolute guarantee that the privacy or confidentiality of
        the personal data or information given or transmitted by the user is
        free from any unfavorable instances that may occur. AC Prime shall not
        be held liable for damages for any loss of confidentiality of any
        information transmitted herein.
      </p>

      <h2 className="mb-2 mt-4 font-semibold">
        5. How Long We Keep Your Information
      </h2>
      <p className="mb-2">
        AC Prime stores your data for five (5) years after account closure.
      </p>
      <p className="mb-4">
        However, your information shall be kept by AC Prime for the fulfillment
        of its obligations and compliance with legal, regulatory, and business
        requirements, or other standards set forth by a governing body.
      </p>
      <h2 className="mb-2 mt-4 font-semibold">6. Your Data Privacy Rights</h2>
      <ul className="mb-4 list-disc pl-5">
        <li>
          Right to Erasure or Blocking: Based on reasonable grounds, you have
          the right to suspend, withdraw or order the blocking, removal, or
          destruction of your personal data from AC Prime’s system.
        </li>
        <li>
          Right to Information: You have the right to be informed about the
          collection, processing, and disposal of your personal data.
        </li>
        <li>
          Right to Object: You have the right to object to the processing of
          your personal data by explicitly withdrawing your consent previously
          provided upon data collection.
        </li>
        <li>
          Right to Access: Upon demand, you have the right to reasonable access
          to the contents of your personal data.
        </li>
        <li>
          Right to Damages: Subject to the results of verification of
          investigation, you may be indemnified for any damages sustained due to
          unauthorized use of your personal data.
        </li>
        <li>
          Right to Data Portability: You have the right to request from AC Prime
          a copy of your personal data that is processed by electronic means in
          a structured or commonly used format.
        </li>
        <li>
          Right to File a Complaint: You have the right to file a complaint with
          AC Prime if you feel that your personal data has been misused,
          maliciously disclosed, or improperly disposed of, or that any of your
          data privacy rights have been violated at
          support@acprimeinsurance.com.
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;
